# Generated by Django 4.1.3 on 2023-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
