# Generated by Django 4.1.3 on 2023-09-22 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)])),
                ('status', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
